apiVersion: v1
kind: Service
metadata:
  name: secure-shield-service
spec:
  type: LoadBalancer
  selector:
    app: secure-shield-landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
