apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-shield-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-shield
  template:
    metadata:
      labels:
        app: secure-shield
    spec:
      containers:
      - name: secure-shield
        image: samavgn/secure-shield:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
